# Generated by Django 5.2.4 on 2025-08-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(help_text='Positivo para incrementar, negativo para decrementar')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('adjustment_type', models.CharField(choices=[('manual', 'Ajuste Manual'), ('inventory_count', 'Conteo de Inventario'), ('damaged', 'Producto Dañado'), ('expired', 'Producto Vencido'), ('other', 'Otro')], default='manual', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.product')),
            ],
        ),
    ]
